import crafttweaker.api.entity.attribute.AttributeOperation;

// ----------------- ALL THESE VALUES ARE ONE (1) LESS THAN THEY APPEAR IN GAME ----------------//
// ---------------------MAKE SURE TO SUBTRACT ONE (1) FROM YOUR INTENDED VALUE ----------------//
// -------------------------- IF IT'S 13 HERE IT WILL BE 14 IN GAME ---------------------------//
<item:predators:earthbreaker>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_EarthBreaker_Damage", 15, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:predators:sultan_of_fegefeuer>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Sultan_Damage", 3, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:predators:prisblade>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Prisblade_Damage", 7, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:epicsamurai:nagamaki>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Nagamki_Damage", 6, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:alexsmobs:skelewag_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Skelewag_Damage", 1, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:epicsamurai:naginata>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Naginata_Damage", 6, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:graveyard:bone_dagger>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Bone_Dagger_Damage", 2, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:aquamirae:terrible_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Terrible_Damage", -10, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);

<item:blue_skies:infused_arc_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Infused_Damage", 14, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:different_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Different_Damage", 14, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:charoite_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Charoite_Damage", 11, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:diopside_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Diopside_Damage", 13, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:pyrope_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Pyrope_Damage", 9, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:aquite_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Aquite_Damage", 10, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:horizonite_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Horizonite_Damage", 10, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:charoite_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_CharoiteA_Damage", 17, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:diopside_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_DiopsideA_Damage", 25, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:pyrope_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_PyropeA_Damage", 14, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:aquite_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_AquiteA_Damage", 14, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:blue_skies:horizonite_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_HorizoniteA_Damage", 16, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:majruszsdifficulty:enderium_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Enderium_Damage", 17, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:enlightened_end:adamantite_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Adamantite_Damage", 14, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:enigmaticlegacy:etherium_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Etherium_Damage", 16, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:majruszsdifficulty:enderium_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_EnderiumA_Damage", 25, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:enlightened_end:adamantite_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_AdamantiteA_Damage", 22, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:enigmaticlegacy:etherium_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_EtheriumA_Damage", 24, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:iter_rpg:elemental_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Elemental_Damage", 20, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:sharpened_dark_metal_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Dark_Metal_Damage", 12, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:great_reaper_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Great_Reaper_Damage", 18, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:nightmare_scythe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Nightmare_Scythe_Damage", 18, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:soul_cutlass>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Soul_Cutlass_Damage", 12, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:intoxicating_dagger>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Intoxicating_Dagger_Damage", 9, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:skullbreaker_hammer>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Skullbreaker_Hammer_Damage", 20, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:trident_hayfork>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Trident_Hayfork_Damage", 13, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:dark_ritual_dagger>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Dark_Ritual_Damage", 9, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:spiritual_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Spiritual_Sword_Damage", 10, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:cataclysm:the_incinerator>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Incinerator_Damage", 22, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:cataclysm:void_forge>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Void_Forge_Damage", 29, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:celestisynth:solaris>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Solaris_Damage", 18, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:celestisynth:crescentia>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Crescentia_Damage", 20, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:celestisynth:breezebreaker>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Breezebreaker_Damage", 12, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:celestisynth:poltergeist>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Poltergeist_Damage", 30, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:celestisynth:aquaflora>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Aquaflora_Damage", 8, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:unusualprehistory:primal_macuahuitl>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Macuahuitl_Damage", 23, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:unusualprehistory:warpick>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Warpick_Damage", 22, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:unusualprehistory:handmade_club>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Handmade_Club_Damage", 23, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:unusualprehistory:handmade_battleaxe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Handmade_Axe_Damage", 24, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:unusualprehistory:handmade_spear>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Handmade_Spear_Damage", 22, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);


<item:enigmaticlegacy:forbidden_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Forbidden_Axe_Damage", 15, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:witherstormmod:command_block_axe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Buff_Command_Axe_Damage", 39, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:witherstormmod:command_block_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage>, AttributeIds.swordAttack, "Nerf_Command_Sword_Damage", 6, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
