
[general]
	#the armor will be divided by this number in calculation
	#Range: 0.01 ~ 1.7976931348623157E308
	armor_dividor = 1.0
	#the toughness will be divided by this number in calculation
	#Range: 0.01 ~ 1.7976931348623157E308
	toughness_dividor = 1.0
	#the base used for armor in calculation
	#Range: 0.0 ~ 1.7976931348623157E308
	armor_base = 0.966
	#the base used for toughness in calculation
	#Range: 0.0 ~ 1.7976931348623157E308
	toughness_base = 0.99

