
[generation]

	[generation.structures]
		#If Jungle in Desert Villages is replaced with Yucca
		"Yucca Desert Villages" = false
		#If Dark Oak in Ancient Cities is replaced with Grimwood
		"Grimwood Ancient Cities" = false

