
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 888414
	#The name of the modpack
	modpackName = "The Chocolate Edition"
	#The version of the modpack
	modpackVersion = "1.8.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true

