
["Config category"]
	#Prints the chest loottable on opening and on spawn and logs the Loottables which do not have a boss assigned of structures to the latest.log. Useful to find the table used by a dungeon chest, only works if the chest is not opened yet: default:false
	printChestLoottableOnOpen = false
	#Global difficulty multiplier, affects health and damage of all bosses
	#Range: 0.1 ~ 1000.0
	globalDifficultyMultiplier = 2.0
	#Global boss spawn chance, determines the chance per treasure chest spawn at which a boss can appear in a structure. Chance X in 100, default = 30
	#Range: 1 ~ 100
	globalBossSpawnChance = 30
	#Minimum distance in blocks between spawning, is not 100% guranteed compares last 20 spawns. default = 100
	#Range: 0 ~ 1000
	minDistance = 100

