
#Artifact Specific Configuration
[artifact_specific_configuration]
	#Entities that can not be converted by Love Medallion.
	loveMedallionBlacklist = ["ender_dragon", "elder_guardian", "wither"]

#Type Loot Table Configuration
[type_loot_table_configuration]
	oceanLootTablesBlacklist = []
	basicLootTablesBlacklist = []
	jungleLootTables = ["dungeons_arise:chests/mushroom_house/mushroom_house_treasure", "dungeons_arise:chests/mushroom_village/mushroom_village_treasure", "dungeons_arise:chests/mushroom_mines/mushroom_mines_treasure", "dungeons_arise:chests/jungle_tree_house/jungle_tree_house_treasure", "idas:chests/treetop_tavern/treetop_tavern_tools", "dungeons_arise:chests/keep_kayra/keep_kayra_library_treasure", "dungeons_arise:chests/keep_kayra/keep_kayra_garden_treasure"]
	desertLootTables = ["idas:chests/labyrinth/labyrinth_treasure", "dungeons_arise:chests/bandit_towers/bandit_towers_treasure", "dungeons_arise:chests/shiraz_palace/shiraz_palace_elite"]
	#This section determines the type of gear found in loot tables, generally based on biomes and dimensions.
	#The whitelist allows gear in, the blacklist bans it from getting gear. Blacklist trumps whitelist.
	#Enter the path of the specific loot table, or the path of the folder containing the loot tables.
	#You can write an incomplete path, and the mod will add to loot tables containing that incomplete path. 
	#Make sure to always include a complete namespace (like minecraft) and at least a partial path.
	basicLootTables = ["dungeons_arise:chests", "idas:chests", "dungeons_arise:chests/thornborn_towers/thornborn_towers_top_treasure", "dungeons_arise:chests/mining_system/mining_system_treasure", "dungeons_arise:chests/illager_fort/illager_fort_treasure", "dungeons_arise:chests/illager_windmill/illager_windmill_treasure", "dungeons_arise:chests/abandoned_temple/abandoned_temple_top", "idas:chests/tinkers_workshop/tinkers_workshop_vault", "idas:chests/castle/castle_throne", "betterdungeons:small_dungeon", "idas:chests/abandonedhouse/abandonedhouse_library", "idas:chests/pillager_fortress/pillager_library", "dungeons_arise:chests/small_blimp/small_blimp_treasure", "betterdungeons:spider_dungeon/chests/egg_room"]
	coldLootTablesBlacklist = []
	endLootTables = ["dungeons_arise:chests/heavenly_rider/heavenly_rider_treasure", "dungeons_arise:chests/heavenly_conqueror/heavenly_conqueror_treasure", "dungeons_arise:chests/heavenly_challenger/heavenly_challenger_treasure", "dungeons_arise:chests/aviary/aviary_treasure"]
	oceanLootTables = ["dungeons_arise:chests/undead_pirate_ship/undead_pirate_ship_treasure", "dungeons_arise:chests/typhon/typhon_treasure", "dungeons_arise:chests/ceryneian_hind/ceryneian_hind_treasure", "idas:chests/sunken_ship/sunken_ship_treasure", "idas:chests/ruins_of_the_deep/ruins_treasure"]
	desertLootTablesBlacklist = []
	netherLootTables = ["idas:chests/haunted_manor/haunted_manor_treasure", "betterdungeons:skeleton_dungeon/chests/middle", "dungeons_arise:chests/foundry/foundry_treasure", "dungeons_arise:chests/scorched_mines/scorched_mines_treasure"]
	netherLootTablesBlacklist = []
	coldLootTables = ["dungeons_arise:chests/plague_asylum/plague_asylum_treasure", "terralith:spire/treasure", "betterdungeons:zombie_dungeon/chests/special"]
	jungleLootTablesBlacklist = []
	endLootTablesBlacklist = []

#Item Configuration
[item_configuration]
	#Set the durability for melee weapons. [0-1024, default: 250
	#Range: 0 ~ 1024
	meleeWeaponDurability = 512

#Rarity Loot Table Configuration
[rarity_loot_table_configuration]
	#This section determines the quality of gear found in loot tables.
	#The whitelist allows gear in, the blacklist bans it from getting gear. Blacklist trumps whitelist.
	#Enter the path of the specific loot table, or the path of the folder containing the loot tables.
	#You can write an incomplete path, and the mod will add to loot tables containing that incomplete path. 
	#Make sure to always include a complete namespace (like minecraft) and at least a partial path.
	commonLootTables = ["idas:chests", "dungeons_arise:chests"]
	obsidianLootTables = ["betterdungeons:small_dungeon", "betterdungeons:nether_small_dungeon", "idas:chests/abandonedhouse/abandonedhouse_library", "idas:chests/treetop_tavern/treetop_tavern_tools", "idas:chests/pillager_fortress/pillager_library", "dungeons_arise:chests/small_blimp/small_blimp_treasure", "betterdungeons:spider_dungeon/chests/egg_room", "betterdungeons:skeleton_dungeon/chests/middle", "betterdungeons:zombie_dungeon/chests/special"]
	commonLootTablesBlacklist = []
	fancyLootTablesBlacklist = []
	obsidianLootTableBlacklist = []
	fancyLootTables = ["dungeons_arise:chests/typhon/typhon_treasure", "dungeons_arise:chests/thornborn_towers/thornborn_towers_top_treasure", "dungeons_arise:chests/scorched_mines/scorched_mines_treasure", "dungeons_arise:chests/shiraz_palace/shiraz_palace_elite", "dungeons_arise:chests/undead_pirate_ship/undead_pirate_ship_treasure", "dungeons_arise:chests/scorched_mines/scorched_mines_treasure", "dungeons_arise:chests/mushroom_village/mushroom_village_treasure", "dungeons_arise:chests/mushroom_mines/mushroom_mines_treasure", "dungeons_arise:chests/mushroom_house/mushroom_house_treasure", "dungeons_arise:chests/plague_asylum/plague_asylum_treasure", "dungeons_arise:chests/monastery/monastery_map", "dungeons_arise:chests/mining_system/mining_system_treasure", "dungeons_arise:chests/keep_kayra/keep_kayra_garden_treasure", "dungeons_arise:chests/keep_kayra/keep_kayra_library_treasure", "dungeons_arise:chests/jungle_tree_house/jungle_tree_house_treasure", "dungeons_arise:chests/illager_fort/illager_fort_treasure", "dungeons_arise:chests/ceryneian_hind/ceryneian_hind_treasure", "dungeons_arise:chests/shiraz_palace/shiraz_palace_treasure", "dungeons_arise:chests/illager_windmill/illager_windmill_treasure", "dungeons_arise:chests/heavenly_rider/heavenly_rider_treasure", "dungeons_arise:chests/heavenly_conqueror/heavenly_conqueror_treasure", "dungeons_arise:chests/heavenly_challenger/heavenly_challenger_treasure", "dungeons_arise:chests/foundry/foundry_treasure", "dungeons_arise:chests/bandit_towers/bandit_towers_treasure", "dungeons_arise:chests/aviary/aviary_treasure", "dungeons_arise:chests/abandoned_temple/abandoned_temple_top", "terralith:spire/treasure", "idas:chests/labyrinth/labyrinth_treasure", "idas:chests/sunken_ship/sunken_ship_treasure", "idas:chests/ruins_of_the_deep/ruins_treasure", "idas:chests/tinkers_workshop/tinkers_workshop_vault", "idas:chests/haunted_manor/haunted_manor_treasure", "idas:chests/castle/castle_throne"]

#Effect Specific Configuration
[effect_specific_configuration]
	#The damage caused by Party Starter. [0-10000, default: 4]
	#Range: 0 ~ 10000
	partyStarterDamage = 4

#Compatibility Configuration
[compatibility_configuration]
	#Enable Project: War Dance compatibility. 
	#Dual wield weapon offhand functions are suppressed in favor of using War Dance's offhand attacks. 
	#Block reach attributes are added to spears so they benefit from skills. 
	#Does nothing if Project: War Dance is not installed. [true / false]
	enableProjectWarDanceCompat = true

#Enchantment Specific Configuration
[enchantment_specific_configuration]
	#The max stacks for dynamo. [0-10000, default: 20]
	#Range: 0 ~ 10000
	dynamoMaxStacks = 20
	#The multiplier increase per level for exploding [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	explodingMultiplierPerLevel = 0.2
	#The amount of damage per trigger of Beast burst. Each trigger causes an explosion around each minion [0-100, default: 5]
	#Range: 0 ~ 100
	beastBurstDamagePerLevel = 5
	#The multiplier increase per level for cowardice [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	cowardiceMultiplierPerLevel = 0.1
	#The decimal base multiplier on the damage for reckless [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	recklessAttackDamageBaseMultiplier = 0.2
	#Multiplier per level applied to the damage. damage * (1 + (configValue*Stacks)) [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	dynamoDamageMultiplierPerStack = 0.1
	#The decimal base chance for a busy bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	busyBeeBaseChance = 0.1
	#Multiplier per level damage to healing conversion. [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	altruisticDamageToHealingPerLevel = 0.25
	#The decimal chance for Chains to trigger [0.0-1.0, default: 0.3]
	#Range: 0.0 ~ 1.0
	chainsChance = 0.3
	#The multiplier increase per level for beast boss [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	beastBossMultiplierPerLevel = 0.1
	#The multiplier increase per level for reckless [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	recklessAttackDamageMultiplierPerLevel = 0.2
	#The decimal base multiplier on the victim's max health for leeching [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	leechingBaseMultiplier = 0.1
	#The decimal base multiplier on the damage for cowardice [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	cowardiceBaseMultiplier = 0.1
	#The decimal chance for rampaging to trigger [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	rampagingChance = 0.2
	#The strength increase per level for Gravity Pulse [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	gravityPulseStrengthPerLevel = 0.1
	#The multiplier increase per level for Frenzied [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	frenziedMultiplierPerLevel = 0.1
	#The duration in ticks (20ticks = 1 second) per level added for rampaging. [0-10000, default: 100]
	#Range: 0 ~ 10000
	rampagingDuration = 100
	#The multiplier to max health for reckless. Balanced as a negative number. [-5.0-5.0, default: -0.6]
	#Range: -5.0 ~ 5.0
	recklessMaxHealthMultiplier = -0.6
	#The decimal base pull strength for Gravity Pulse [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	gravityPulseBaseStrength = 0.1
	#The decimal chance per level added for a busy bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	busyBeeChancePerLevel = 0.1
	#The multiplier increase per level for max damage committed [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	committedMultiplierPerLevel = 0.25
	#The amount of souls per trigger of Soul Siphon. Each souls will give a value based on Soul Gathering. [0-100, default: 2]
	#Range: 0 ~ 100
	soulSiphonSoulsPerLevel = 2
	#The duration in ticks of the speed boost applied by Beast Surge. [0-10000, default: 200]
	#Range: 0 ~ 10000
	beastSurgeDuration = 200
	#The application distance in blocks for weakening. [0-10000, default: 5]
	#Range: 0 ~ 10000
	weakeningDistance = 5
	#The decimal chance for Radiance to trigger [0.0-1.0, default: 0.2]
	#Range: 0.0 ~ 1.0
	radianceChance = 0.2
	#The decimal chance per level added for a tumble bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	tumbleBeeChancePerLevel = 0.1
	#The decimal base multiplier on the damage for max damage committed.  [0.0-5.0, default: 1.25]
	#Range: 0.0 ~ 5.0
	committedBaseMultiplier = 1.25
	#The chance per level for Stunning to trigger [-5.0-5.0, default: 0.25]
	#Range: -5.0 ~ 5.0
	stunningChancePerLevel = 0.1
	#The chance per level for beehive to trigger [-5.0-5.0, default: 0.25]
	#Range: -5.0 ~ 5.0
	beehiveChancePerLevel = 0.1
	#The decimal base multiplier on the minions's damage for beast boss [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	beastBossBaseMultiplier = 0.1
	#The chance per level for dodge to trigger [-5.0-5.0, default: 0.25]
	#Range: -5.0 ~ 5.0
	dodgeChancePerLevel = 0.01
	#The duration in ticks (20ticks = 1 second) for weakening. [0-10000, default: 100]
	#Range: 0 ~ 10000
	weakeningDuration = 100
	#The base damage for Thundering [0-10000, default: 5]
	#Range: 0 ~ 10000
	thunderingBaseDamage = 5
	#The chance per level for deflect to trigger [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	deflectChancePerLevel = 0.2
	#The multiplier increase per level for Focus Enchantments [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	focusMultiplierPerLevel = 0.25
	#The multiplier increase per level for leeching [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	leechingMultiplierPerLevel = 0.2
	#The duration in ticks (20ticks = 1 second) for freezing. [0-10000, default: 60]
	#Range: 0 ~ 10000
	freezingDuration = 60
	#The chance per level for void dodge to trigger [-5.0-5.0, default: 0.25]
	#Range: -5.0 ~ 5.0
	voidDodgeChancePerLevel = 0.05
	#The decimal chance for Soul Siphon to trigger [0.0-1.0, default: 0.05]
	#Range: 0.0 ~ 1.0
	soulSiphonChance = 0.05
	#The chance for Poison Cloud to trigger [-5.0-5.0, default: 0.3]
	#Range: -5.0 ~ 5.0
	prospectorChancePerLevel = 0.3
	#The decimal chance for Thundering to trigger [0.0-1.0, default: 0.3]
	#Range: 0.0 ~ 1.0
	thunderingChance = 0.3
	#The decimal base duration for Potion Barrier [0-10000, default: 60]
	#Range: 0 ~ 10000
	potionBarrierBaseDuration = 60
	#The duration in ticks (20ticks = 1 second) per level added for rushdown. [0-10000, default: 20]
	#Range: 0 ~ 10000
	rushdownDuration = 20
	#The duration increase per level for Potion Barrier [0-10000, default: 20]
	#Range: 0 ~ 10000
	potionBarrierDurationPerLevel = 20

#General Mod Configuration
[general_mod_configuration]
	#Enable melee weapons appearing in chest loot and trades. 
	#If you Ewant to disable obtaining this mod's melee weapons, disable this feature. [true / false]
	enableMeleeWeaponLoot = true
	#Enable melee weapons appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableMeleeWeaponTab = true
	#Add enchantments that should be designated as treasure-only. 
	#To do so, enter their registry names.
	treasureOnlyEnchantments = ["dungeons_gear:masters_call"]
	#Enable the addition of Dungeons Gear items to the Minecraft Spawn Bonus chest. 
	#Theoretically, this can be controlled through the loot tables, this option is added for additional control. [true / false]
	enableDungeonsGearLootOnBonusChest = false
	#The emerald value for an artifact [0-64, default: 24]
	#Range: 0 ~ 64
	artifactValue = 24
	#Enable applying enchantments from this mod on non-Dungeons gear using the Enchanting Table. 
	#If you don't want your enchantments to become too cluttered for non-Dungeons gear, or simply don't like it, disable this feature. 
	#You can still use the anvil to put the enchantments onto them and have them work correctly. [true / false]
	enableEnchantsOnNonDungeonsGear = false
	#The emerald value for a common weapon or armor [0-64, default: 12]
	#Range: 0 ~ 64
	commonItemValue = 12
	#Enable artifacts appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableArtifactTab = true
	#Enable Librarian Villagers trading books enchanted with this mod's enchantments. 
	#Disable this feature if you want to prevent this. [true / false]
	enableEnchantmentTrades = false
	#Enable ranged weapons appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableRangedWeaponTab = true
	#Enables the experimental features.
	#If you like living on the edge with broken items, enable this feature. [true / false]
	enableExperimental = false
	#The emerald value for a unique weapon or armor [0-64, default: 24]
	#Range: 0 ~ 64
	uniqueItemValue = 24
	#Enable enchantments from this mod appearing in any type of generated loot. 
	#Disable this feature if you want to prevent this. [true / false]
	enableEnchantmentLoot = true
	#Enable Friendly Fire on Pets 
	#If you dislike (or outright hate) your pets and would like to kill them, enable this feature. [true / false]
	enableFriendlyPetFire = true
	#Enable ranged weapons appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's ranged weapons, disable this feature. [true / false]
	enableRangedWeaponLoot = true
	#Enable armors appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableArmorTab = true
	#Enable Weaponsmith, Fletcher, Armorer and Leatherworker Villagers trading Dungeons Gear items. 
	#If you have other mods messing with the trades of those professions or simply don't want it, disable this feature. [true / false]
	enableVillagerTrades = false
	#Enable artifacts appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's artifacts, disable this feature. [true / false]
	enableArtifactLoot = true
	#Enable applying enchantments together to create combinations would  be considered too overpowered. 
	#If you don't want overpowered enchantment combinations, like Sharpness and Committed on a sword, disable this feature. [true / false]
	enableOverpoweredEnchantmentDualWields = false
	#Enable the mass addition of Dungeons Gear items to various vanilla loot tables by the mod itself. 
	#If you prefer to write your own loot pools via datapack or simply don't want it, disable this feature. [true / false]
	enableDungeonsGearLoot = true
	#Add enchantments that should be prevented from being applied to any gear. 
	#To do so, enter their registry names.
	enchantmentBlacklist = ["dungeons_gear:lucky_explorer"]
	#Enable the salvaging of Dungeons Gear items by shift-right clicking villagers with the item in your hand. 
	#If you have other mods messing with shift-right clicking villagers or simply don't want it, disable this feature. [true / false]
	enableSalvaging = true
	#Enable armors appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's armors, disable this feature. [true / false]
	enableArmorLoot = true

