
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD mini mode
	invMini = true
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD alpha
	#Range: 0 ~ 100
	invAlpha = 10
	#Toggle on by default
	byDefault = false
	#Animate recently picked up items
	animatedInv = true
	#Hide background if inventory is empty
	hideBackground = true

#Settings for ArmorStatus HUD
[armorhud]
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Show/Hide armor
	showArmor = true
	#Show/Hide armor
	showMain = true
	#Show/Hide armor
	showOff = true
	#Show/Hide armor
	showArrows = true
	#Show/Hide armor
	showInv = true
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT, OFF
	armView = "OFF"
	#Show item durability bar
	armBars = true
	#Move all items at once or each one
	moveAll = false
	#Show/Hide empty slot icon
	showEmpty = false
	#Show overall count of items in main/off hand
	showCount = true
	#ArmorHUD scale in persentage from 50 to 150
	#Range: 50 ~ 150
	armScale = 75

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 60
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = 0
	#Potion HUD mini mode
	potMini = true
	#Potion HUD horizontal mode
	potHor = true
	#Full bar duration
	#Range: > 1
	barDuration = 300

#DONT TOUCH THESE FIELDS!
[positions]
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "BOTTOM"
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "MIDDLE"
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 0
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 116
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "MIDDLE"
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 0
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 70
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "TOP"
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "LEFT"
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 9
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 5
	#Helmet position (X)
	#Range: -9999 ~ 9999
	helmPosX = 84
	#Helmet position (Y)
	#Range: -9999 ~ 9999
	helmPosY = 15
	#Chestplate position (X)
	#Range: -9999 ~ 9999
	chestPosX = 93
	#Chestplate position (Y)
	#Range: -9999 ~ 9999
	chestPosY = 29
	#Leggings position (X)
	#Range: -9999 ~ 9999
	legPosX = 93
	#Leggings position (Y)
	#Range: -9999 ~ 9999
	legPosY = 80
	#Boots position (X)
	#Range: -9999 ~ 9999
	bootPosX = 84
	#Boots position (Y)
	#Range: -9999 ~ 9999
	bootPosY = 95
	#MainHand position (X)
	#Range: -9999 ~ 9999
	mainPosX = 101
	#MainHand position (Y)
	#Range: -9999 ~ 9999
	mainPosY = 44
	#OffHand position (X)
	#Range: -9999 ~ 9999
	offPosX = 101
	#OffHand position (Y)
	#Range: -9999 ~ 9999
	offPosY = 64
	#Arrows position (X)
	#Range: -9999 ~ 9999
	arrPosX = 106
	#Arrows position (Y)
	#Range: -9999 ~ 9999
	arrPosY = 38
	#InvIcon position (X)
	#Range: -9999 ~ 9999
	invPosX = -105
	#InvIcon position (Y)
	#Range: -9999 ~ 9999
	invPosY = 37
	#Helmet horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	helmHal = "RIGHT"
	#Helmet vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	helmVal = "TOP"
	#Chestplate horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	chestHal = "RIGHT"
	#Chestplate vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	chestVal = "TOP"
	#Leggings horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	legHal = "RIGHT"
	#Leggings vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	legVal = "TOP"
	#Boots horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	bootHal = "RIGHT"
	#Boots vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	bootVal = "TOP"
	#MainHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	mainHal = "RIGHT"
	#MainHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	mainVal = "TOP"
	#OffHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	offHal = "RIGHT"
	#OffHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	offVal = "TOP"
	#Arrows horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	arrHal = "MIDDLE"
	#Arrows vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	arrVal = "BOTTOM"
	#InvIcon horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHal = "MIDDLE"
	#InvIcon vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invVal = "BOTTOM"

