[rules."minecraft:overworld"]
firelightspawn = "false"
fallenchaosknightspawn = "false"
zombieclownspawn = "false"
skeletonthrasherspawn = "false"
zombielumberjackspawn = "false"
bonescallerspawn = "false"
zombiebruiserspawn = "false"
skeletonbombspawn = "false"
bloodygadflyspawn = "false"
maggotsappearance = "false"
spiritguidespawn = "false"
zombiefishermanspawn = "false"
dreadhoundspawn = "false"
theappearanceoftheNightmareStalker = "false"
darkvortexspawn = "false"
missionaryspawn = "false"
decayingzombiespawn = "false"
maggotsAppearance = "false"
boneimpspawn = "false"
thornshellcrabspawn = "false"
babyskeletonspawn = "false"
restlessspiritspawn = "false"
fallenChaosKnightSpawn = "false"
gluttonfishspawn = "false"
generationofinfecteddiamonds = "false"
decrepitskeletonspawn = "false"
corpseflyspawn = "false"
zombiesinabarrel = "false"
phantomcreeperspawn = "false"
doorknightspawn = "false"
corpsefishspawn = "false"
[rules."minecraft:the_nether"]
doMobLoot = "true"
