
["Minecraft Default Totem Features"]
	#This value sets the health Totem of Undying will give to the entity upon use. DEFAULT: 1
	#Range: 1 ~ 20
	"Set Health" = 1
	#When Totem of Undying is used it removes all previous effects you had. If set to false, it will keep all the effects you had before using the totem. DEFAULT: TRUE
	"Remove All Effects" = false

	["Minecraft Default Totem Features".Effects]
		#If false Totem of Undying will not give you fire resistance effect. DEFAULT: TRUE
		"Enable Fire Resistance" = true
		#Sets the duration of the fire resistance effect in ticks. DEFAULT: 800
		"Fire Resistance Duration" = 800
		#If false Totem of Undying will not give you regeneration effect. DEFAULT: TRUE
		"Enable Regeneration" = true
		#Sets the duration of the regeneration effect in ticks. DEFAULT: 900
		"Regeneration Duration" = 900
		#Sets the amplifier of the regeneration effect. DEFAULT: 1
		#Range: 0 ~ 255
		"Regeneration Amplifier" = 1
		#If false Totem of Undying will not give you absorption effect. DEFAULT: TRUE
		"Enable Absorption" = true
		#Sets the duration of the absorption effect in ticks. DEFAULT: 100
		"Absorption Duration" = 100
		#Sets the amplifier of the absorption effect. DEFAULT: 1
		#Range: 0 ~ 255
		"Absorption Amplifier" = 1

["New Totem Features"]
	#If true you will be able to use the Totem of Undying from your inventory. DEFAULT: FALSE
	"Use Totem From Inventory" = false

	["New Totem Features".Effects]
		#Apply fire resistance and water breathing effects only when needed, meaning you are going to receive the effects only if you are on fire or in water respectively. DEFAULT: TRUE
		"Apply Effects Only When Needed" = true
		#If false Totem of Undying will not give you water breathing effect. DEFAULT: TRUE
		"Enable Water Breathing" = false
		#Sets the duration of the water breathing effect in ticks. DEFAULT: 800
		"Water Breathing Duration" = 800
		#If false Totem of Undying will not give you slow falling effect. DEFAULT: TRUE
		"Enable Slow Falling" = false
		#Sets the duration of the slow falling effect in ticks. DEFAULT: 600
		"Slow Falling Duration" = 600

		["New Totem Features".Effects."Custom Effects"]
			#Use this list to add custom effects and specify when they should be triggered. Within this list, you should provide another list using curly braces, with the first parameter being the damage type, the second parameter being the effect that will be granted, the third parameter the duration of the effect in ticks, and the fourth parameter the effect amplifier. If you want the effect to always be granted, use the damage type as "any". Example: [["outOfWorld", "minecraft:blindness", 800, 0]]. In this example, if the player dies in the void, the totem will grant the level 1 blindness effect with a duration of 40 seconds. If you don't know which damage types can be used, see the wiki on GitHub. DEFAULT: Nothing
			"Custom Effects" = [[]]

	["New Totem Features"."Increase Food Level"]
		#If false Totem of Undying will not increase your food level. DEFAULT: TRUE
		"Increase Food Level" = false
		#Sets the minimum food level needed to Totem of Undying increase food level. DEFAULT: <= 6
		#Range: 0 ~ 20
		"Minimum Food Level" = 6
		#Sets the food level that Totem of Undying will give upon use. DEFAULT: 8
		#Range: 0 ~ 20
		"Set Food Level" = 8

	["New Totem Features"."Destroy Blocks When Suffocating or Fully Frozen"]
		#If false Totem of Undying will not break blocks when you are suffocating. DEFAULT: TRUE
		"Destroy Blocks When Suffocating" = false
		#If false Totem of Undying will not break the powder snow when you die fully frozen. DEFAULT: TRUE
		"Destroy Powder Snow When Fully Frozen" = false

	["New Totem Features"."Knockback Mobs Away"]
		#If false Totem of Undying will not knockback mobs away. DEFAULT: TRUE
		"Knockback Mobs Away" = false
		#Sets the radius where entities needs to be for the totem knockback them. DEFAULT: 3.0
		"Knockback Radius" = 3.0
		#Sets the strength of the knockback. DEFAULT: 2.5
		"Knockback Strength" = 2.5

	["New Totem Features"."Teleport Out of Void"]
		#If false Totem of Undying will not save you from dying in the void. DEFAULT: TRUE
		"Teleport Out of Void" = false
		#If totem can't find a available position to teleport you back it will teleport you to the world's max build height plus this offset. DEFAULT:64
		#Range: 0 ~ 1024
		"Teleport Height Offset" = 64

	["New Totem Features"."Add Cooldown"]
		#If true Totem of Undying will receive a cooldown after being used and you will not be able to use it again during this period. DEFAULT: FALSE
		"Add Cooldown" = false
		#Sets the cooldown duration in ticks. DEFAULT: 200
		Cooldown = 2000

[Curios]
	#If false you will not be able to use Totem of Undying from charm slot (Curios mod must be installed). DEFAULT: TRUE
	"Use Totem From Charm Slot" = true
	#If false Totem of Undying will not be displayed on the chest when worn in the curios charm slot (Curios mod must be installed). DEFAULT: TRUE
	"Display Totem on Chest" = false

[Blacklists]
	#You can put here dimensions where you don't want Totem of Undying to work. Example: "minecraft:overworld", "mod_id:dimension_id" DEFAULT: Nothing
	"Blacklisted Dimensions" = []
	#You can put here structures where you don't want Totem of Undying to work. Example: "minecraft:desert_pyramid", "mod_id:structure_id" DEFAULT: Nothing
	"Blacklisted Structures" = []

