
#General Settings
[general]
	#How long does the player need to be sleeping in order
	#for entity despawning to occur? | Default: 50
	#Range: 1 ~ 100
	sleepTimer = 50
	#Check to see if it's too close to morning for despawning? | Default: true
	sleptLateCheck = true
	#Should check and disable entity despawning around other
	#non-sleeping players withing range? | Default: true
	playerCheck = true
	#Enables individual mob despawns instead of group despawning. | Default: false
	enableList = false
	#List of mobs to despawn.
	#Formatting: ["minecraft:creeper", "minecraft:zombie", "minecraft:spider", "modid:entityname"]
	mobs = ["minecraft:creeper", "minecraft:zombie", "minecraft:spider"]

#Range Settings
[ranges]
	#Should scaling based on difficulty be enabled? | Default: true
	enableScaling = true
	#Vertical range to check for mobs to despawn. | Default: 16
	#Scaling: EASY = base | NORMAL = base / 2 | HARD = base / 4
	#Range: 0 ~ 64
	verticalRange = 16
	#Horizontal range to check for mobs to despawn. | Default: 64
	#Scaling: EASY = base | NORMAL = base / 2 | HARD = base / 4
	#Range: 0 ~ 256
	horizontalRange = 64
	#Range in which mobs are considered too close to despawn.
	#Disabled if scaling isn't enabled or when set to 0. | Default: 2.5
	#Scaling: EASY = Disabled | NORMAL = base | HARD = base * 2
	#Range: 0.0 ~ 5.0
	antiCheese = 2.5

