#Slows the mining speed of budding amethyst
slowedBuddingAmethystMiningSpeed = true
#Adds silver ingot to pillager drops
pillagerDropSilverIngot = true
#Adds spectre flares to ancient city loot
spectreFlareAncientCityLoot = true

