
["Client Settings"]
	#Setting this to false will disable camera shakes.
	cameraShakesAllowed = true
	#Setting this to true will turn on Arachnophobe-Safe Mode, Ragno will become a horrifying monstrosity in a different way
	arachnophobeMode = false

