
["Queen Bee Configs"]
	#If true enables Queen Bee boss bar. DEFAULT: FALSE
	"Enable Boss Bar" = true
	#If false bees will not drop stinger. DEFAULT: TRUE
	"Enable Bees Dropping Stinger" = true

	["Queen Bee Configs"."Summon Angry Bees Attack"]
		#If false Queen Bee will not summon angry bees during battle. DEFAULT: TRUE
		"Enable Summon Angry Bees" = true
		#Sets the amount of angry bees to spawn. DEFAULT: 3
		"Angry Bees Amount" = 3
		#Sets the cooldown of the attack in ticks. DEFAULT: 200
		"Summon Angry Bees Cooldown" = 200

	["Queen Bee Configs"."Poison Nimbus Attack"]
		#If false Queen Bee will not summon a poison nimbus during battle. DEFAULT: TRUE
		"Enable Poison Nimbus" = true
		#Sets the maximum distance entity can be for the attack to be executed. The real value passed here is the square root of this value, e.g. 49 = 7 blocks of distance. DEFAULT: 49
		"Target Maximum Distance" = 49
		#Sets the poison nimbus area effect cloud duration in ticks. DEFAULT: 40
		"Poison Nimbus Duration" = 40
		#Sets the area effect cloud size. DEFAULT: 7
		"Poison Nimbus Radius" = 7
		#Sets the duration in ticks of the poison effect. DEFAULT: 200
		"Poison Effect Duration" = 200
		#Sets the amplifier of the poison effect. DEFAULT: 1
		"Poison Effect Amplifier" = 1
		#Sets the cooldown of the attack in ticks. DEFAULT: 200
		"Poison Nimbus Cooldown" = 200

["Stinger Sword Configs"]
	#If false right click ability of stinger sword will not work. DEFAULT: TRUE
	"Enable Cure Bee" = true
	#Sets the regeneration area effect cloud duration in ticks. DEFAULT: 200
	"Regeneration Area Effect Cloud Duration" = 200
	#Sets the regeneration area effect cloud size. DEFAULT: 4
	"Regeneration Area Effect Cloud Radius" = 4
	#Sets the duration in ticks of the regeneration effect. DEFAULT: 40 
	"Regeneration Effect Duration" = 40
	#Sets the amplifier of the regeneration effect. DEFAULT: 1
	"Regeneration Effect Amplifier" = 1
	#If false stinger sword will not inflict nausea effect. DEFAULT: TRUE
	"Enable Nausea Effect" = true
	#Sets the duration in ticks of the nausea effect. DEFAULT: 300
	"Nausea Effect Duration" = 300
	#If false stinger sword will not inflict poison effect. DEFAULT: TRUE
	"Enable Poison Effect" = true
	#Sets the duration in ticks of the poison effect. DEFAULT: 100
	"Poison Effect Duration" = 100
	#Sets the amplifier of the poison effect. DEFAULT: 0
	"Poison Effect Amplifier" = 0
	#Sets Stinger Sword cooldown in ticks after using right click ability. DEFAULT: 900
	"Stinger Sword Cooldown" = 900
	#If false will disable stinger sword tooltip. DEFAULT: TRUE
	"Enable Stinger Sword Tooltip" = true

["Antenna Configs"]
	#If false antenna will not prevent bees aggro on you. DEFAULT: TRUE
	"Enable Antenna" = true
	#If false will disable antenna only in the bumblezone dimension. DEFAULT: TRUE
	"Enable Antenna Bumblezone Dimension" = true
	#If false will disable antenna tooltip. DEFAULT: TRUE
	"Enable Antenna Tooltip" = true

