
["Sculk Horn Mod"]
	#Range: 0 ~ 10000
	distance_DURABILITY = 500
	#Range: 1.0 ~ 10000.0
	distance_DAMAGE = 8.0
	#Range: 0 ~ 10000
	distance_COOLDOWN = 200
	#Range: 0 ~ 10000
	distance_EXPERIENCE_LEVEL = 5
	#Range: 1 ~ 10000
	distance_USE_TIME = 10
	#Range: -10000 ~ 10000
	distance_REMOVE_EXPERIENCE = -55
	#Range: 0 ~ 10000
	distance_DISTANCE = 16

