#Should Ender Dragon Eggs replenish on the exit portal after a respawned dragon is deafeated?
#Useful for multiplayer scenarios.
replenish_eggs = true
#Should dragon eggs generate in treasure chest loot tables?
#Useful for multiplayer scenarios and offering alternative ways to obtain eggs.
#Different types of egg breeds can be found in different chests (if configured.)
use_loot_tables = false
#Should Dragon Eggs adapt to their environments and change breeds?
update_habitats = true
#Number of times a dragon is able to breed.
#Range: > 0
breed_limit = 2

