
["Sculk Horn Mod"]
	#Range: 1.0 ~ 10000.0
	area_Damage = 12.0
	#Range: -10000 ~ 10000
	area_REMOVE_EXPERIENCE = -55
	#Range: 0 ~ 10000
	area_SPEED_AMPLIFIER = 0
	#Range: 0 ~ 10000
	area_SPEED_DURATION = 30
	#Range: 0 ~ 10000
	area_DURABILITY = 350
	#Disable or enable the speed given to the player after using the Area Sculk Horn
	area_SPEED = true
	#Range: 0 ~ 10000
	area_EXPERIENCE_LEVEL = 5
	#Range: 0 ~ 10000
	area_cooldown = 300
	#Range: 1.0 ~ 10000.0
	area_RADIUS = 3.5

