
["Base Damage Modifications (Temporarily Unusable)"]
	#Define the base attack damage of the Solaris.
	#Range: 0 ~ 1000
	"Base Damage: Solaris" = 9
	#Define the base attack damage of the Crescentia.
	#Range: 0 ~ 1000
	"Base Damage: Crescentia" = 10

#Some attacks deal a specified amount of damage FOR EVERY HIT, so be careful as you tweak these values!
# 
["Value Modifiers - Solaris"]
	#Define how much damage does the Solaris deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Spinning Flames - Full Round" = 2.0
	#Define how much damage does the Solaris deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Spinning Flames - Soul Straight Dash [Shift]" = 1.6
	#Define the duration of the cooldown provided by the Solaris in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Spinning Flames - Full Round" = 130
	#Define the duration of the cooldown provided by the Solaris in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Spinning Flames - Soul Straight Dash [Shift]" = 200

["Value Modifiers - Crescentia"]
	#Define how much damage does the Crescentia deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Lunar Celebration Barrage" = 1.0
	#Define how much damage does the Crescentia deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Dragon Crescent Boom [Shift]" = 0.75
	#Define the duration of the cooldown provided by the Crescentia in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Lunar Celebration Barrage" = 160
	#Define the duration of the cooldown provided by the Crescentia in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Dragon Crescent Boom [Shift]" = 160

["Value Modifiers - Breezebreaker"]
	#Define how much damage does the Breezebreaker deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Galestorm + Dual Galestorm" = 10.0
	#Define how much damage does the Breezebreaker deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Full-Force Whirlwind Extravagance [Shift]" = 1.25
	#Define how much damage does the Breezebreaker deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Roar of the Wind [Sprint]" = 16.5
	#Define how much damage does the Breezebreaker deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Zephyr's Death Wheel [Mid-air]" = 12.0
	#Define the duration of the cooldown provided by the Breezebreaker in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Galestorm + Dual Galestorm" = 15
	#Define the duration of the cooldown provided by the Breezebreaker in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Full-Force Whirlwind Extravagance [Shift]" = 35
	#Define the duration of the cooldown provided by the Breezebreaker in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Roar of the Wind [Sprint]" = 15
	#Define the duration of the cooldown provided by the Breezebreaker in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Zephyr's Death Wheel [Mid-air]" = 40

["Value Modifiers - Poltergeist"]
	#Define how much damage does the Poltergeist deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Cosmic Steel Annihilation" = 30.5
	#Define how much damage does the Poltergeist deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Barrier Call" = 10.0
	#Define the duration of the cooldown provided by the Poltergeist in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Cosmic Steel Annihilation" = 200
	#Define the duration of the cooldown provided by the Poltergeist in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Barrier Call" = 10

["Value Modifiers - Aquaflora"]
	#Define how much damage does the Aquaflora deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Petal Pierces" = 0.75
	#Define how much damage does the Aquaflora deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Blasting Off Together" = 10.0
	#Define how much damage does the Aquaflora deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Exorbitant Slashing Frenzy" = 1.85
	#Define how much damage does the Aquaflora deal in a specified attack skill.
	#Range: 0.0 ~ 1000.0
	"Damage: Flowers Away" = 0.0
	#Define the duration of the cooldown provided by the Aquaflora in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Petal Pierces" = 60
	#Define the duration of the cooldown provided by the Aquaflora in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Blasting Off Together" = 40
	#Define the duration of the cooldown provided by the Aquaflora in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Exorbitant Slashing Frenzy" = 180
	#Define the duration of the cooldown provided by the Aquaflora in a particular attack skill, measured in ticks.
	#Range: 0 ~ 1000
	"Cooldown: Flowers Away" = 40

["Value Modifiers - Rainfall Serenity"]
	#Define how much damage does the Rainfall Serenity's Arrow deal.
	#Range: 0.0 ~ 1000.0
	"Damage: Rainfall Serenity Arrow" = 12.0
	#Define how much damage does the Rainfall Serenity's Arrow from Quasar Link deal.
	#Range: 0.0 ~ 1000.0
	"Damage: Rainfall Serenity Arrow (Quasar)" = 8.0
	#Define how much damage does the Rainfall Serenity's Arrow from Quasar Link deal.
	#Range: 0.0 ~ 1000.0
	"Extra: Rainfall Serenity Draw Speed" = 40.0

